### ISSUE TITLE
[Quick Question]How does it work?

### ISSUE THREAD

**Issue by NameLord** [zzerexx/scripts#3]
Like for example everything it decompiled succesfully but what can i do w/this ?
it says in one of the files this

```
--   ['source'] = @
--   ['what'] = Lua
--   ['numparams'] = 0
--   ['func'] = function: 0x000000002200711b
--   ['short_src'] = 
--   ['name'] = 
--   ['currentline'] = 1164
--   ['namewhat'] = function
--   ['is_vararg'] = 0
--   ['nups'] = 2
```
what this means? this is not code..
edit-1 Sorry for bad english my native is Romanian
edit-2 Used Pro Script Dumper.

**Comment by zzerexx** [comment]
its the info of the function, which was from debug.getinfo
